runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin


libraries:
- name: jinja2
  version: latest
